### ISSUE TITLE
clean up license info for base64binary.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#13]
sherpa/base64binary.js has this comment that was added to it by @jbphet:

> TODO: I (jblanco) don't think that this is licensed such that PhET can just
> use it.  Its use is temporary while exploring ways to handle the audio.

sherpa/info.js indicates that base64binary.js is used by sims:

> 40  usage: ['sim']

The 3rd-party spreadsheet  indicates that it's used by vibe. See https://docs.google.com/spreadsheets/d/1XWlHFidztUT6ARb7yHQ1Naepd6L0x9LF94AAoKHGaWg/edit#gid=0

**Comment by jbphet** [comment]
The dependency on base64binary has been removed, see https://github.com/phetsims/vibe/issues/15.  I've removed the corresponding entry from the spreadsheet as well.  Nothing left to do here, closing.

**Comment by samreid** [comment]
> I've removed the corresponding entry from the spreadsheet as well. Nothing left to do here, closing.

I'm wondering if the base64binary entry should remain in the spreadsheet until all vibe sims have been redeployed.  My thought is that the spreadsheet should probably indicate not what is in *master* but what is in production on our website.

**Comment by jbphet** [comment]
Good point.  I've restored it to the spreadsheet and have added the following text to the "How is it used..." section:
>  Deprecated - this dependency was removed in early May 2015, but this entry should be retained until the lib isn't present in any published sims.

**Comment by samreid** [comment]
That looks perfect, thanks!
