### ISSUE TITLE
text.js appears twice

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#15]
We have two identical copies of text.js with different filenames.  We should remove the unversioned one.

**Comment by samreid** [comment]
Fixed one ref in https://github.com/phetsims/chipper/commit/e41ed7d0ff8fb95fa1c9d86ca3ee849a2cf1e281 and tested by building RPAL and inspecting HTML.

**Comment by pixelzoom** [comment]
@samreid I see lots of commits above the replaced `text` with `text-2.0.12`, but `text` is still in info.js.  Can it be deleted?

**Comment by pixelzoom** [comment]
Since "text" no longer exists in sherpa, I'm deleting it from info.js. Closing.

**Comment by samreid** [comment]
It looks like Quantum Bound States is using sherpa/text:
https://github.com/alecmartin/quantum-bound-states/blob/master/js/quantum-bound-states-config.js

We should write them a note that lets them know how they can upgrade to the versioned text file so things won't break when they pull latest master sherpa.

**Comment by samreid** [comment]
I created an issue in quantum bound states: https://github.com/alecmartin/quantum-bound-states/issues/41.  Closing.
