### ISSUE TITLE
use JSON for license info file?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#16]
sherpa/info.js contains license info and is read by the build process. Since this is a data file, why aren't we using json?  It could be read with `grunt.file.readJSON`, as we're doing for package.json.

**Comment by pixelzoom** [comment]
Perhaps info.js could also be responsible for specifying which licenses need to be included in the HTML deliverable for all sims?

**Comment by pixelzoom** [comment]
@samreid Is there any reason why info.js was written as a module.exports instead of JSON?

**Comment by samreid** [comment]
Skimming through info.js, it seems like it could be rewritten to use JSON instead of JS.  I originally thought info.js might require variables/loops/etc but I think it is now more of just a data file that could use JSON.

**Comment by samreid** [comment]
> Perhaps info.js (or info.json) could also be responsible for specifying which licenses need to be included in the HTML deliverable for all sims?

Yes, that seems like a nice place to capture this information.

**Comment by pixelzoom** [comment]
Investigating converting to JSON... The first thing I ran into is that multi-line strings are not supported in JSON.  So (for example) this:

```js
    text: "Bootstrap v2.2.2\n" +
            "Copyright 2012 Twitter, Inc\n" +
            "Licensed under the Apache License v2.0\n" +
            "http://www.apache.org/licenses/LICENSE-2.0\n" +
            "Designed and built with all the love in the world @twitter by @mdo and @fat.",
[5/11/15, 12:07:46 PM] Chris Malley: For readability, I'm reluctant to convert this to a single-line string.
```

would need to be converted to this:

```
"text": "Bootstrap v2.2.2\nCopyright 2012 Twitter, Inc\nLicensed under the Apache License v2.0\nhttp://www.apache.org/licenses/LICENSE-2.0\nDesigned and built with all the love in the world @twitter by @mdo and @fat.",
```

I'm reluctant to change this because it is dramatically less readable.  Is there another way to do this?...

**Comment by pixelzoom** [comment]
Moved the issue of where to specify common licenses to https://github.com/phetsims/sherpa/issues/18.

**Comment by pixelzoom** [comment]
Work on this is completed. Assigning to @jonathanolson since he seems to be most conversant on JSON format.

**Comment by jonathanolson** [comment]
Looks good to me.
