### ISSUE TITLE
specify common licenses in info.json ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#18]
Perhaps info.json could also be responsible for specifying which licenses need to be included in the HTML deliverable for all sims.  

Currently these specified are in setLicenseText.js, and there's an opportunity for the keys to get out of sync with info.son:

```js
var licenseKeys = [
    // dependencies common to all sims that are NOT preloaded
    'almond-0.2.9',
    'font-awesome',
    'pegjs-0.7.0',
    'require-i18n',
    'text-2.0.12'
  ];
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sherpa/issues/16#issuecomment-100454639, @samreid said:
> Yes, that seems like a nice place to capture this information.

**Comment by samreid** [comment]
On the other hand, it looks like info.js is just a list of all libraries and their usages.  If we want to have a named list (string array) of dependencies across all sims, it probably belongs elsewhere (possibly another file in sherpa).  If we want to include this information in info.js then, perhaps adding a new value to "usage" like "all-sims" or something like that.  Then iterating through all entries, we can find which ones are "all-sims" and hence in the list.  I'm not sure which of these options is superior, can we discuss it @pixelzoom?

**Comment by pixelzoom** [comment]
How about if chipper had a build.json file? Example below. There would be "common" and "together" objects, each with "preload" and "licenseKeys" metadata. This stuff is currently inlined in setPreload.js and setLicenseText.js.

```
{
  "common": {
    "preload": [
      "../sherpa/lib/jquery-2.1.0.js",
      "../sherpa/lib/lodash-2.4.1.js",
      "../sherpa/lib/has-70898c7.js",
      "../sherpa/lib/FileSaver-b8054a2.js",
      "../assert/js/assert.js",
      "../chipper/js/initialize-globals.js",
      "../phetcommon/js/analytics/google-analytics.js"
    ],
    "licenseKeys": [
      "almond-0.2.9",
      "font-awesome",
      "pegjs-0.7.0",
      "require-i18n",
      "text-2.0.12"
    ]
  },
  "together": {
    "preload": [
      "../sherpa/lib/jsondiffpatch-0.1.31.js",
      "../together/js/together.js",
      "../together/js/SimIFrameAPI.js",
      "../together/js/togetherEvents.js",
      "../together/js/datamite.js",
      "../together/js/api/TogetherCommon.js"
    ],
    "licenseKeys": []
  }
}
```

**Comment by pixelzoom** [comment]
The above file would be read using something like:

`var buildInfo = grunt.file.readJSON( '../sherpa/build.json' );`

**Comment by pixelzoom** [comment]
Assigning to @samreid for his opinion on build.json.

**Comment by pixelzoom** [comment]
I went ahead and implemented build.json.  Seemed like a good place to capture all of the "common" stuff that sims specify in package.json.  I named it build.json because it's associated with the grunt "build" task, but open to a better name.

**Comment by pixelzoom** [comment]
5/19/15 dev meeting: Looks good as is, close issue.
