### ISSUE TITLE
Remove version numbers from sherpa library filenames.

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#2]
Some of the sherpa libs have versions in their filenames, such as ```require-2.1.8.js```.  This makes it easy to see the version number but difficult to upgrade multiple sims to new versions.  For many of the libraries (including requirejs), the version number is readily available in the top few lines of the code.  Also, we probably do not want to support multiple versions of libraries in a single runtime (such as a sim using both require 2.1.8 and require 2.1.9).  Also, the file provided by require.js is named ```require.js``` and updating files 'in-place' can make diffs slightly easier (to see what changed between versions).  So I am leaning toward stripping the version numbers.  Since this has been controversial in the past, I won't proceed without further discussion.

**Comment by pixelzoom** [comment]
We decided to do the opposite - add version numbers to all libs.  See https://github.com/phetsims/sherpa/issues/14.

Closing.
