### ISSUE TITLE
bootstrap license: Apache or MIT?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#20]
For bootstrap-2.2.2, info.json says "Licensed under the Apache License v2.0". The Google Drive license spreadsheet says Apache, but links to an MIT license (https://github.com/twbs/bootstrap/blob/master/LICENSE). 

Is this an error or has bootstrap changed their license?

**Comment by samreid** [comment]
It looks like master changed.  Let's point to a tag:
https://github.com/twbs/bootstrap/blob/v2.2.2/LICENSE

@pixelzoom can you please update the spreadsheet link?

**Comment by pixelzoom** [comment]
Can we just point to a new license without updating the library? If version 2.2.2 was indeed licensed under Apache, then we shouldn't change the license until we update to a version that has the MIT license.

**Comment by samreid** [comment]
> Can we just point to a new license without updating the library?

Yes, that is what I recommended when I said "Let's point to a tag:" and provided a link to the 2.2 (Apache) license in https://github.com/phetsims/sherpa/issues/20#issuecomment-101772617

**Comment by pixelzoom** [comment]
OK, I'll fix the spreadsheet and info.js.

**Comment by samreid** [comment]
Thank you @pixelzoom

**Comment by pixelzoom** [comment]
Done, closing.
