### ISSUE TITLE
Switch to modern bootstrap

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#21]
In https://github.com/phetsims/sherpa/issues/20 @pixelzoom identified that the bootstrap license changed from Apache to MIT.  I think it simplifies things somewhat to move more of our 3rd party libraries to MIT, so perhaps it would be good for @jonathanolson to update bootstrap usages to use a more modern bootstrap (unless it is too complicated).

**Comment by pixelzoom** [comment]
@jonathanolson If/when you update to a more recent Bootstrap, please update the license in sherpa/info.js and all of the relevant info in the license spreadsheet (on Google Drive).

**Comment by jonathanolson** [comment]
If I recall correctly, moving from bootstrap 2 to 3 included major breaking changes. How much time would this be worth?

**Comment by samreid** [comment]
In my opinion, it would be worth 0.5 hours to download the new bootstrap, test it, enumerate issues (if any) and make a time estimate for upgrading.  Let's check with @ariel-phet though since he is more in touch with our work scheduling.

**Comment by samreid** [comment]
We determined that Apache is an acceptable license for our usage, so I think this issue can be closed with no work.
