### ISSUE TITLE
add version number to liberation-sans-regular-subset-numeric-degrees.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#23]
Some discussion about this in #14, but I don't know how to proceed. Assigning this to @jonathanolson as a separate issue, since he added this library.  Please update both sherpa/info.json and the 3rd-party license spreadsheet on Google Drive.

**Comment by samreid** [comment]
This code has been stable since 2015.  If we add another version, we can add a filename at that time (if we don't overwrite the original).  Closing.
