### ISSUE TITLE
Remove require-i18n things

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#26]
In #25 @pixelzoom identified that require-i18n has an entry in info.json but no license specified.  @samreid pointed out that we are no longer using require-i18n since we have created our own string plugin for internationalization.  We need to remove the entry from info.json and an entry from chipper/build.json.

**Comment by samreid** [comment]
I removed all the references I could find above.  Reassigned to @pixelzoom to double check (a) that we are indeed not using require-i18n (b) that I got all of the references in my 2 commits above and (c) there is nothing left to do here.

**Comment by pixelzoom** [comment]
Looks good, closing.
