### ISSUE TITLE
Incorrect font-awesome version in third-party-licenses.json

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sherpa#32]
It's definitely not 4.3.0 for what we're using, as our icon names don't exist there. The icon prefix looks to be in 3.x (e.g. http://fortawesome.github.io/Font-Awesome/3.2.1/icons/), not the latest version.

@samreid, can you identify which version of font-awesome was used, and optionally check in the needed content so we could regenerate the file?

**Comment by pixelzoom** [comment]
I believe that the content file is sherpa/libs/font-awesome.txt (or something like that, going from memory, can't check right now.)

**Comment by jonathanolson** [comment]
> I believe that the content file is sherpa/libs/font-awesome.txt (or something like that, going from memory, can't check right now.)

Yup, https://github.com/phetsims/sherpa/blob/master/lib/font-awesome.txt

**Comment by samreid** [comment]
This was introduced in svn Commit: 72724 By samreid on 09 Apr 2013 22:44, we can probably use that to determine the font awesome version number.

**Comment by samreid** [comment]
According to the font awesome history

> very early pass at 3.1.0
> davegandy authored on Apr 2, 2013

So I think this is a "good enough" guess for the version of Font Awesome that we are using.

**Comment by samreid** [comment]
Last commit from 3.0.2 tag is Jan 17, 2013.  Last commit from 3.1.0 is May 10, 2013, so perhaps we were using 3.0.2, since I was using a release (not from github master)

**Comment by samreid** [comment]
I found an identical match based on content diff here:

https://raw.githubusercontent.com/FortAwesome/Font-Awesome/v3.0.2/font/fontawesome-webfont.svg

**Comment by samreid** [comment]
According to https://github.com/FortAwesome/Font-Awesome/tree/v3.0.2 

> The Font Awesome font is licensed under the SIL Open Font License - http://scripts.sil.org/OFL

but

> The Font Awesome pictograms are licensed under the CC BY 3.0 License - http://creativecommons.org/licenses/by/3.0/

We are using the pictograms, not the font, so we'll need to update our license accordingly.

**Comment by samreid** [comment]
I am very confused--I looked in the font files (TTF and OTF) and they contain pictograms.  We are using the text from the SVG file, so I guess that is considered pictograms.  The other complication is that it says the pictograms are CC BY 3.0, but it also says after CC BY 3.0:

> Attribution is no longer required in Font Awesome 3.0, but much appreciated: "Font Awesome by Dave Gandy - http://fortawesome.github.com/Font-Awesome"

"By" means attribution required, but "Attribution is no longer required" contradicts this.  So confusing.

**Comment by samreid** [comment]
I recommend to change the filename to match the one on the web.

**Comment by samreid** [comment]
@ariel-phet do you want a graphic artist to redesign these iconic fonts we are using so we can steer clear of this licensing confusion? We are currently using:

cut
times_circle
fullscreen
home
reorder
check_without_box
warning_sign
eye_close
eye_open
warning_sign
volume_up
volume_off
check
check_empty

**Comment by samreid** [comment]
I did not see any usages of font-awesome.txt so I am proceeding to rename it.

**Comment by samreid** [comment]
Renamed and updated the third-party-licenses.json above.  But I also noted that the file is "fontawesome-webfont-3.0.2" so I am back to being confused about whether we are technically using the "pictograms" or the "font", since "webfont" is in the filename that we are using.

**Comment by samreid** [comment]
Also it is in the "font" directory--this begs the question: what exactly are the pictographs?  

But this page explains:
http://fortawesome.github.io/Font-Awesome/license/

> SIL OFL Applies to all desktop and webfont files in the following directory: font-awesome/fonts/.

In the latest version, the directory is "fonts" and it contains the SVG. In the 3.0.2, the directory is "font" and it contains the SVG.  So I think we can infer that we should be using the SIL OFL (as we have), not the CC BY 3.0.

**Comment by samreid** [comment]
Reassigning to @ariel-phet to respond to the last few comments.

**Comment by samreid** [comment]
@ariel-phet said we won't be redrawing these icons at the moment.  @samreid will review the SIL OFL to see if any other work is required.

**Comment by samreid** [comment]
I read through http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web and did not see any troublesome language, closing.

**Comment by samreid** [comment]
Reopening, we never changed the license from CC-BY to SIL after discovering that pictograms are covered under the SIL.
