### ISSUE TITLE
Determine which license issues should be marked for S2015R (Summer 2015 Redeploy)

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#37]
In https://github.com/phetsims/sherpa/issues/22#issuecomment-119023356 we wanted to discuss which of the licensing issues (if any) should be marked for Summer 2015 Redeploy.

It may be sufficient to make sure the license information that gets bundled into the built simulation is correct, but would be good to discuss & verify.

**Comment by samreid** [comment]
@ariel-phet said making sure the license information that gets bundled into the sim seems like a good threshold, and we can do this on a sim-by-sim basis to start.  Code review phase seems too late, perhaps this should be in the RC testing checklist?  Not really sure where to add this.  @ariel-phet can you suggest a place?

**Comment by ariel-phet** [comment]
@samreid - what do you think about a redeploy checklist...seems like it might be useful to develop. That way that can become an issue for each sim we redeploy, and ensure we do not miss any steps.

**Comment by ariel-phet** [comment]
Perhaps lets make a sample list here and then put it in phet-info when ready?

@samreid - thoughts/addition/clarifcations to the list below?

- [ ] Review outstanding issues, mark what will be addressed for redeploy
- [ ] Review and update licensing info
- [ ] Some sort of test for seeing if common repos are stable (grunt or such)
- [ ] Any sort of translation beta test necessary?
- [ ] Perform RC testing
- [ ] Address RC issues and publish
- [ ] Check teacher tips are up to date
- [ ] Check sim primer is up to date

**Comment by ariel-phet** [comment]
@pixelzoom - can you also look at the preliminary list I created above and suggest any additions/clarifications

**Comment by pixelzoom** [comment]
Since the focus of this redeploy is translations, I'd like to see the "translation beta test" item fleshed out a more.  Perhaps:

- [ ] stringTest=double
- [ ] stringTest=X
- [ ] stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingThatDoubleDidNotExpose
- [ ] Rosetta test (whatever that is)
- [ ] RTL language test

**Comment by pixelzoom** [comment]
I'm wondering why this checklist is being discussed in this issue? Recommend to move it to an issue in tasks repo, titled something like "sim-specific checklist for Summer 2015 Redeploy".

**Comment by samreid** [comment]
I looked through current licensing issues https://github.com/issues?q=is%3Aissue+is%3Aopen+label%3Alicensing+user%3Aphetsims+sort%3Acreated-asc and marked 2 or 3 for S2015R.  I'll move the S2015R redeploy checklist to a new tasks issue and close this one.
