### ISSUE TITLE
Look through third-party-licenses.md and make sure everything looks good

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#39]
@kathy-phet pointed out some `undefined` today, we should look through everything and make sure it is ready to go.

**Comment by samreid** [comment]
I've iterated through this many times and clicked through the project and license links and everything seems okay to me.  @ariel-phet I'm not sure if you want to go the extra mile and request someone else to double check everything in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md  (mainly that the project URLs look right, go to the right place and I have correctly identified the license name and obtained the correct license text for each project).

**Comment by ariel-phet** [comment]
@samreid - I did a quick skim, and some spot checking. Everything looks good to me. I will also add a checklist item to our redeploy checklist to compare a sims licenses to the the spreadsheet so it gets some extra checking. Closing.
