### ISSUE TITLE
Add "Appears in Published Simulations: " field, if easy

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#42]
@kathy-phet said if it is easy to add an "Appears in Published Simulations" field, we should do so.

**Comment by pixelzoom** [comment]
That's going to be a headache to keep accurate. We'll have to remember when we stop using libraries in a sim. And when we republish that sim, we'll need to determine if any versions of sims currently on the website still use the libraries that the sim being published has stopped using.  It's going to be about as complicated to determine as it is to describe :)

**Comment by samreid** [comment]
Agreed, this would be feasible if we just had to track what is currently in master, but we previously decided we need to track what is published on the website, so this would be an order of magnitude more complex.  I'll close it as "will not complete".
