### ISSUE TITLE
Review all licenses for 3rd party code that appears in simulations to see if they are OK

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#43]
@kathy-phet wanted to verify that our 3rd party code appearing in simulations is not problematic.

**Comment by samreid** [comment]
The licenses appearing in our simulations are:

The MIT License
SIL Open Font License, Version 1.1
Revised BSD License
Public Domain
Use it if you like it

I read through all of the licenses and the only bit that seems potentially problematic is this section of the SIL Open Font License:

> 5) The Font Software, modified or unmodified, in part or in whole,
must be distributed entirely under this license, and must not be
distributed under any other license. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.

Since we are including the font awesome glyphs and the liberation numeric fonts (for molecule shapes) I am wondering if we can relicense that as GPL.  The term "GPL compatible" is often the one used for discussing this sort of thing.  It looks like someone asked this exact question on the font awesome site:
https://github.com/FortAwesome/Font-Awesome/issues/1124

To summarize: the creator and maintainer of font awesome, said:

> I like the phrase "GPL friendly." Here's what I've tried to do with Font Awesome:
> * make the most open licensing possible, while still being actually licensed
> * I want Font Awesome to be able to be used for commercial projects
> * avoid viral nature of GPL

However, they decided to change the phrase "GPL compatible" to "GPL friendly".  According to the FSF, there is a significant legal difference between delivering the font graphics alongside the GPL code (aggregated together) vs *combined* with the GPL code.  Please see this comment: https://github.com/FortAwesome/Font-Awesome/issues/1124#issuecomment-29507471
I am unclear on the technical/legal distinction between aggregation and combination.

Since this issue applies to both font awesome and the liberation fonts for molecule shapes, I would recommend that we discuss it with our legal counsel.  I reviewed my past correspondence with Molly and, while we discussed Font Awesome, it was on a different subject (the missing copyright statement), so this is a new question.  An alternative would be to write to the authors such as the creator of Font Awesome and ask for specific permission or a custom license agreement.  Dave Gandy did say:

> For any specific concerns about adding Font Awesome to your open source project, please feel free to contact me directly.

Yet another alternative would be to re-create artwork ourselves, but that would be quite a bit of work since we use many font awesome glyphs and the molecule-shapes font data would be tedious to recreate (and may not end up looking as good as the original).

The internet says MIT and revised BSD are both GPL compatible, so no issues there.

@ariel-phet can you please review everything and suggest next steps?

**Comment by kathy-phet** [comment]
We don't actually license the minified file as GPL. We license that as CC-BY, which is appropriate because it is a single object and its context of use. Only the individual repositories we build up on Github are GPL (or otherwise). 

It sounds like FA would support the use in theory. I would like to understand better how the code appears in and is integrated into our code. They keep saying documents created using FA are not subject to the license. Then I will talk with Molly for legal advice.

**Comment by samreid** [comment]
@kathy-phet & I reviewed how font awesome appears in the sim code today.  I am much less concerned about this issue now that I know that the minified sim is CC-BY instead of GPL.  @kathy-phet said she will still review this with our legal counsel.

**Comment by kathy-phet** [comment]
I looked at the details of the Font Awesome license. It all looks compatible to me, so I agree that this is not concerning with use in a CC-BY license product. I will have Molly take a look, though.

**Comment by samreid** [comment]
Sounds good.  We're planning to start the summer redeploy process on Monday--I don't think this should push that back, but if you discover problems please let us know right away.

**Comment by kathy-phet** [comment]
Molly responded:

**Comment by kathy-phet** [comment]
Assigning back to Sam to close if he feels it is all resolved.

**Comment by samreid** [comment]
Thanks @kathy-phet, I think this issue is complete, closing.
