### ISSUE TITLE
Add BSD license for easing equations

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#45]
Tween.js is attributed like so:

```js
  "Tween-r12.js": {
    "text": [
      "Copyright (c) 2010-2012 Tween.js authors.",
      "Easing equations Copyright (c) 2001 Robert Penner under BSD license"
    ],
    "license": "The MIT License",
    "licenseURL": "see http://robertpenner.com/easing_terms_of_use.html",
    "projectURL": "https://github.com/tweenjs/tween.js/",
    "notes": "Used to smoothly animate the speedometer and accelerometer to the left and back in Forces and Motion Basics."
  }
```

However, the fact that part of tween.js is covered by MIT and part covered by BSD should be elucidated in our metadata.  This will be complicated because our convention is thus far: one license per file.

**Comment by samreid** [comment]
Ideas for dealing with this:
1. separate out the easing equations into a separate file.  This would mean all tween.js clients would have to point to the 2 files
2. call the license for this one "The MIT License and BSD License".  This would look like a separate license type.  We could concatenate the licenses into a single file so they would both be included.
3. Add a separate entry for easing equations and make sure each tween client points to it as an "additional license dependency"
4. Creating more complex data structures in the licenses json, such as one entry depending on another, etc.  This could make several things more complex and brittle.

At the moment (2) seems the least offensive (less invasive and less opportunity to forget to include the right licenses).

**Comment by samreid** [comment]
Another option: make it so that each file can have multiple license metadatas.

**Comment by samreid** [comment]
A few other projects fit into this category: for instance, jquery includes jsizzle.  Though in that case it is the same license and the same copyright statement, since both are from the same group.  Lodash gives attribution to underscore, and provides underscore's copyright statement.  benchmark-1.0.0.js is based on jslitmus.

**Comment by samreid** [comment]
I've decided to do the following:
1. create a separate license entry in third-party-licenses.json/md for easing-equations
2. include the license text for easing equations
3. add a new file in chipper requires easing-equations to be included if tween is included (errors out if not)

Working on this, I tested grunt with bending-light (after adding an entry to package.json licenseKeys) and it is properly including the easing-equations license.  I tested grunt for hookes-law without adding to licenseKeys and it correctly failed the build.  I tested with `grunt build-no-lint` with ohms-law, which does not include tween.js and it finished the build and the html correctly doesn't include easing-equations.

I iterated over every project that uses tween.js and added licenseKeys with easing-equations.  Will commit shortly after further testing.

**Comment by samreid** [comment]
I ran grunt-all.sh and did not see any issues related to the easing equations.  Will commit soon.

**Comment by samreid** [comment]
Committed changes above.  Had git errors for chipper, capacitor lab and quantum-bound-states.  I'm looking into it.

For capacitor lab, it looks like as of today it no longer uses tween.  I have recloned the repo.
For chipper, it looks like it generated a merge commit.  @aaronsamuel137 can you check that I didn't disrupt anything?  I'm a little fuzzy on merge commits.
For quantum bound states, I don't have commit priviliges--this means I should probably post to the Google Group.

**Comment by samreid** [comment]
I posted this to the google group:

PhET Simulations sometimes use the Tween.js library which is built with Robert Penner's Easing Equations.  Since the easing equations have a different license than the tween library that includes them, we must add an attribution in the package.json file so it will include the licenses properly into the compiled HTML file.  Here is a commit showing the code to add to package.json (for projects that use tween), which is:

"licenseKeys": [
 "easing-equations"
]

I've also updated chipper so that if a project is including tween.js but doesn't have a license key for easing-equations, the build will fail.  More details available at the GitHub issue.

Best Regards,
Sam Reid

**Comment by samreid** [comment]
Reassigning to @pixelzoom to review the changes to chipper, if/when you have time.

**Comment by aaronsamuel137** [comment]
Merge commit looks good. Nothing disrupted.

**Comment by pixelzoom** [comment]
> 3. add a new file in chipper requires easing-equations to be included if tween is included (errors out if not)

Sorry, I don't like this approach at all.  It's a patch for a specific case, not a robust/general solution. 

A better approach would be to add an optional "dependences" field to entries in third-party-licenses.json. Then automatically add any libs that are listed.

For example, for Tween, the entry would be:

```js
"Tween-r12.js": {
     ...
    "dependences": "easing-equations"
  },
```

In setThirdPartyLicenses.js, add this after line 77:

```js
// Add all dependences. Duplicates will be removed later.
for ( var i = 0; i < licenseKeys.length; i++ ) {
   if ( licenseInfo[ licenseKeys[i].dependencies ] ) {
      licenseKeys = licenseKeys.concat( licenseKeys[i].dependencies ); 
   } 
}
```

Assigning to @samreid for comment.

**Comment by pixelzoom** [comment]
Btw... The above also has the advantage that we don't have to remember to include "easing-equations" every time we include "Tween-r12.js".

**Comment by samreid** [comment]
The proposal to add an optional `dependencies` as array[string] sounds great, I'll do it for the next version.

**Comment by pixelzoom** [comment]
Ah yes, "dependencies" should be `string[]`. I amended the example in https://github.com/phetsims/sherpa/issues/45#issuecomment-122013352.

**Comment by samreid** [comment]
I've made the changes above (which also address #52 and #50), tested by building with grunt for hookes-law and energy-skate-park-basics and inspecting their html to see that the dependencies are included properly, and by launching hookes-law.  I'll commit shortly.

**Comment by samreid** [comment]
Fixed above and reassigned to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great, thanks. Closing.

**Comment by pixelzoom** [comment]
Reopening. @samreid you should probably amend your Google Group post.

**Comment by samreid** [comment]
I sent out a new message on the google groups thread, thanks @pixelzoom.  Closing.
