### ISSUE TITLE
Update canvg from 1.2 to 1.3

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#5]
Our sherpa is using canvg 1.2 but I noticed 1.3 is out.

@jonathanolson can you look into this?  I'm not sure how canvg is used or how to test it.

**Comment by samreid** [comment]
Not sure how I would test whether it is working properly, so I'm going to leave this up to @jonathanolson when he decides the time is right.

**Comment by jonathanolson** [comment]
Tested recently.
