### ISSUE TITLE
Does pixi require additional licenses?

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#51]
I saw another copyright statement within the pixi code while I was passing by.  We should take a look whether it requires auxiliary licenses.

**Comment by samreid** [comment]
In my opinion, we should eliminate pixi and focus our efforts on the scenery implementation of WebGL.  If we decide to use pixi again, we should address the licensing issues then.

**Comment by samreid** [comment]
Pixi appears in many places and would be quite a bit of work to remove.  We should make sure we are in agreement about how to proceed here before removing things.  See also the many scenery pixi issues: https://github.com/phetsims/scenery/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+pixi

**Comment by jonathanolson** [comment]
> In my opinion, we should eliminate pixi and focus our efforts on the scenery implementation of WebGL. If we decide to use pixi again, we should address the licensing issues then.

In your opinion, would it be worth keeping to see if future versions would improve reordering so they would require fewer draw calls?

**Comment by samreid** [comment]
It is difficult to say.  It all depends on what issues we run into while developing scenery.webgl, what our time estimates for evaluating pixi v3+ are, etc.  Perhaps once we get time allocated back to webgl we should discuss this in-person and/or as a group.

**Comment by samreid** [comment]
I removed pixi, closing.
