### ISSUE TITLE
move font-related stuff to sherpa/fonts/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#55]
Broken out from https://github.com/phetsims/chipper/issues/175#issuecomment-127265301.

sherpa/lib/ is intended to contain 3rd-party code, and third-party-license.json was renamed license.json (see https://github.com/phetsims/sherpa/issues/54).  So it would make sense to move font-related files to sherpa/fonts/, with its own license.json.

**Comment by samreid** [comment]
liberation-sans-regular-subset-numeric-degrees.js is on the fence between font and code.  It is technically a javascript code library that provides font.  Where should it live?

And I'm not even sure we need font-awesome checked in, since all of the derived data is elsewhere.  We just need to be able to specify its license.

Reassigning to @pixelzoom for discussion.

**Comment by pixelzoom** [comment]
I think it's useful to have liberation-sans-regular-subset-numeric-degrees.js and fontawesome-webfont-3.0.2.svg checked in, given our difficulties in locating these in the past.

I would classify liberation-sans-regular and font-awesome as code, and drop the "fonts" category from documentation, reports, etc.

**Comment by samreid** [comment]
I changed references from "code and fonts" to "code" throughout chipper and tested by building hookes-law, and running the built and requirejs hookes-law and inspecting the HTML.  I did not double check the composite license report (takes 30+ minutes to generate, and should be done when we run that task again).  Seemed good so I'll commit.

**Comment by samreid** [comment]
I committed my changes locally but am receiving this error when I try to push:

fatal: unable to access 'https://github.com/phetsims/chipper.git/': Server aborted the SSL handshake

Twitter github status doesn't show anything awry at the moment.

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/chipper/commit/8fa1a2731a86ae4b739f8626193ff5308345100d, closing.
