### ISSUE TITLE
Update instructions for how to update the third-party-licenses.md file

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sherpa#56]
I updated three.js to r71, including adding two dependencies as discussed.

The README here notes to run "grunt update-third-party-licenses-md", but:
```
Warning: Task "update-third-party-licenses-md" not found. Use --force to continue.
```

What process needs to be done to update this?

**Comment by samreid** [comment]
@pixelzoom and I are in the process of improving how this is done.  We'll have to run a composite report once that is working properly again.  I'll leave it assigned to me to take care of, but noting that since three.js remained MIT in r71 it didn't introduce any new licensing encumbrances.

**Comment by samreid** [comment]
I can run this after (a) building everything (b) parsing the version info out of the HTML.

**Comment by samreid** [comment]
I updated the instructions above and regenerated the report.  @jonathanolson can you take a look and let me know if you have recommendations.

**Comment by pixelzoom** [comment]
Pinging @jonathanolson for review.

**Comment by jonathanolson** [comment]
Instructions still seem out of date. Built all sims, copied HTMLs to git/tmp, then:
```
grunt report-third-party --copy-from-build --input=../tmp/
Running "report-third-party" task
Warning: missing required option: input Use --force to continue.

Aborted due to warnings.
```
There's also a required 'output' attribute (do I have to point that to the third party report?), and I don't see --copy-from-build. Maybe that's --activeRunnables now?

If it's going to be this complicated every time I make a sherpa change, can we create a chipper/bin/generate-third-party-report.sh that does all of the tasks?

**Comment by samreid** [comment]
The instructions were stale and confusing.  I revised them in the above commit and tested them.  Can you take a look @jonathanolson ?

**Comment by jonathanolson** [comment]
Instructions look good, applied minor formatting fix for list.
