### ISSUE TITLE
Regenerate the licensing report

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#57]
Since the version of three.js changed for Molecule Shapes, we need to update the third-party-licenses.md file, see #56

**Comment by samreid** [comment]
The new version is live:
https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

Closing.

**Comment by pixelzoom** [comment]
Looks generally awesome, nice job!

I do have one suggestion about formatting, not sure if it belongs in this issue.  I see some entries that look like this:

```
BUILD_A_MOLECULE/green-left.png


License: Unknown
Notes:
```

This would be easier to read without the blank lines, especially when there are contiguous entries like this.

**Comment by samreid** [comment]
I think that stems from a missing or blank entry, I'll create a new issue for it.
