### ISSUE TITLE
Can we remove easel and jquerymobile?

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#6]
Can we remove easel & jquerymobile from sherpa now?  AFAIK we had it checked it for a comparison to scenery--and I'm not sure it's valuable any more.

EDIT: added 'jquerymobile'

**Comment by pixelzoom** [comment]
@jonathanolson Do these dependencies exist in any scenery branches? Can this issue be closed?

**Comment by jonathanolson** [comment]
Some older performance comparisons between Easel, manually implemented and Scenery use it.

It's not particularly important, I can scrap it if helpful.

**Comment by pixelzoom** [comment]
@jonathanolson This is up to you. Either remove the dependencies, or add their license information to sherpa/info.json and the 3rd-party license spreadsheet on Google Drive.

**Comment by pixelzoom** [comment]
Still a licensing issue. Easel is used in scenery and masses-and-springs, but not referenced in sherpa/info.json or the 3rd-party license spreadsheet on Google Drive.

**Comment by jonathanolson** [comment]
I'll plan on removing them shortly.

**Comment by jonathanolson** [comment]
Removed references and old 'easel-performance-test' from Scenery.

Should we remove references in faraday/masses-and-springs?

**Comment by samreid** [comment]
I'd like to delete masses-and-springs in https://github.com/phetsims/masses-and-springs/issues/4

What is the faraday reference?

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> Should we remove references in faraday/masses-and-springs?

I was the author of the faraday 'experiment', and I'm surprised to find that it still runs. If/when we port faraday from Java, we'll likely wipe most of this repo. But there may be some stuff that can be salvaged (model, e-field,...)  It's not in active-repos, and isn't something that PhET plans to publish.  So if PhET is ok with the license implications, it may be best to leave as is.

I don't know who's responsible for masses-and-springs or what state it's in.

**Comment by samreid** [comment]
Masses and springs has been deleted, @jessegreenberg @jbphet @pixelzoom @jonathanolson @aaronsamuel137 please remove your working copy and pull chipper to get the new list of active-repos.

**Comment by samreid** [comment]
All other easel & jquerymobile references are in docs or comments, closing.

**Comment by pixelzoom** [comment]
Have we verified that PhET is OK with leaving faraday as is?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sherpa/issues/6#issuecomment-155201340, I wrote:
>  So if PhET is ok with the 3rd-party licensing implications, it may be best to leave [faraday] as is.

Have we verified that PhET is OK with leaving faraday as is?

**Comment by samreid** [comment]
Ah I see, I wasn't aware of https://github.com/phetsims/faraday (different than faradays-law) and its usages of Easel.  Thanks for helping me understand.  I'm not entirely sure if we should delete it.  It is technically redistributing easel and other libs without a statement.  But on the other hand, the sim is not destined for production so its risk is probably very low.  Some options:

1. Leave it as it is
2. Download an archive copy, delete the repo and use the archived copy for reference when we start the port.
3. Remove the contrib files from the repo, point to a CDN or something
4. Add license info to the sim.

In my opinion, any of these options would probably be fine.

**Comment by ariel-phet** [comment]
@samreid what is the status of this issue? why do we have the /faraday repo at all?

**Comment by ariel-phet** [comment]
please mark for developer meeting if necessary

**Comment by samreid** [comment]
@pixelzoom do any of the options in https://github.com/phetsims/sherpa/issues/6#issuecomment-155211800 strike your fancy?

**Comment by pixelzoom** [comment]
@ariel-phet asked:
> why do we have the /faraday repo at all?

This was an early port of portions of Faraday's Electromagnetic Lab.  Looking at what's currently there, there's a significant amount of code that would be straightforward to move from Easel to Scenery.  So this could serve as a nice start on this sim, when PhET decides to port it.  The downside is that there are a bunch of 3rd-party libraries in faraday/contrib/ (jquery, easel, i18n, image, require, tpl) that are not being handled via PhET's standard "sherpa" repo. That said...

@samreid asked:
> @pixelzoom do any of the options in https://github.com/phetsims/sherpa/issues/6#issuecomment-155211800 strike your fancy?

Any of these would be OK, since they preserve the work that's been done.  The lowest cost option is (1) Leave as is.  But since this involves licensing issues, I'll defer to @ariel-phet for a decision.

**Comment by pixelzoom** [comment]
Btw... Note that Easel no longer exists in sherpa, so wrt this issue, sherpa is clean.

**Comment by ariel-phet** [comment]
I made faraday a private repo. Since we are not sharing with anyone or publishing, I am unconcerned about the licensing issues in faraday and we can address when we port (and make the repo not private again) closing this issue and referencing in https://github.com/phetsims/faraday/issues/1

**Comment by samreid** [comment]
Clever plan, nice work, +1

**Comment by pixelzoom** [comment]
Excellent solution.
