### ISSUE TITLE
report-third-party and hookes-law published

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/sherpa#60]
I just published hookes-law, and saw the following instructions in https://github.com/phetsims/phet-info/blob/master/sim_deployment.md:

>The 3rd party contributions page must be updated. Directions for how to do this are in reportThirdParty.js.
Brace yourself-- this will take >30 minutes since you will need to build all of the simulations in order to access their 3rd party encumbrances. After running this, the updated third-party-licenses.md file should be checked in to GitHub, which will make it publicly available to people who click on "3rd party contributions" from the sim. If this process is too cumbersome, in the future we can discuss ways to just generate a report for the new sim and integrate it into the existing report.

However it looks like ```grunt report-third-party``` has a few different options and I wasn't sure what to do here.

Assigning to @samreid to take care of this or clarify the instructions.

**Comment by samreid** [comment]
Finished above, quick summary of what I did:

```
grunt-all.sh 
grunt report-third-party --input=/Users/samreid/temp/input --output=/Users/samreid/temp/output.md --active-runnables=true
```
Paste over third-party-licenses.md and commit.
