### ISSUE TITLE
Remove JSHint

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#63]
We are no longer using JSHint and it can be removed.

**Comment by samreid** [comment]
I've removed JSHint and many references to it.  I left several JSHint references that seemed like they were indicating a suboptimal implementation in order to satisfy JSHint, many occurrences in Kite and Scenery.  @jonathanolson can you take a look and see if any code changes should be made?

**Comment by jonathanolson** [comment]
Didn't see any jshint references in Scenery/Kite. I'll tackle anything related as I notice.
