### ISSUE TITLE
Report 3rd party libraries (and media?) for HTML simulations on the website

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#67]
In https://github.com/phetsims/sherpa/issues/64#issuecomment-232995908 @mattpen said:

@samreid - To get this data in the database, I think the easiest option would be to modify your script so that it creates a second file in json format with the 3rd party information and sends it to the website in a POST request. This will make it easier to parse in tomcat. Is it ok with you if I add that to the script, or should I wait until after CM reviews it?

Now that the script has been reviewed by @pixelzoom and the approach of getting HTML from the website seems good, you are clear to continue with getting this to the website.

@mattpen feel free to convert this to a website issue if that's preferable.

**Comment by mattpen** [comment]
@samreid - I'm having some trouble running the script.  On my machine, the strings that result from `activeSimsString.split( '\n' );` appear to end in a carriage return.   I had to change [this line](https://github.com/phetsims/chipper/blob/master/js/grunt/reportThirdParty.js#L330) to the following in order to get the script to work.

`var url = 'http://192.168.56.102/sims/html/' + sim.substring( 0, sim.length - 1 ) + '/latest/' + sim.substring( 0, sim.length - 1 ) + '_en.html';`

Have you encountered this problem? My initial hypothesis is that my github checkout method is wrong since I am on a windows machine and CR and LF are handled differently.

**Comment by pixelzoom** [comment]
@mattpen See https://help.github.com/articles/dealing-with-line-endings/

I see that you also changed `phet.colorado.edu` to `192.168.56.102`. You didn't mention why, so I'm assuming that it's unrelated.

**Comment by mattpen** [comment]
@pixelzoom - Thanks.  192.168.56.102 is my local version of the website.  That won't be checked into github.

**Comment by mattpen** [comment]
The current reportThirdParty.js script will fail on the new server (phet-new).  The downloaded files are not following the redirect to https, and grunt is preventing https protocol from being used.

This is the result for the file download if I point it at `http://phet-new...`:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://phet-new.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html">here</a>.</p>
</body></html>
```

If I change the requested url to start with `https://phet-new...`, I get the following errors, and the downloaded file is empty:
```
$ grunt report-third-party
Running "report-third-party" task
downloading 1/72: https://phet-new.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html
Warning: Protocol "https:" not supported. Expected "http:". Use --force to continue.

Aborted due to warnings.

$ grunt report-third-party --force
Running "report-third-party" task
downloading 1/72: https://phet-new.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_en.html
Warning: Protocol "https:" not supported. Expected "http:". Used --force, continuing.

Done, but with warnings.
```

**Comment by pixelzoom** [comment]
Do the html files live on the server where the task is being run? If so, then you could read the files via their local pathnames, instead of via http.  (Or does this task need to be still be runnable on development machines?)

**Comment by mattpen** [comment]
@pixelzoom - It works if I use the [https module ](https://nodejs.org/api/https.html) instead of `http`.  Do you see any reason not to use https?

i.e.
```
var https = require( 'https' )
https.get( url, dest, cb )
...
```

**Comment by pixelzoom** [comment]
I know of any reason not to use https.  But then again, I'm not totally clear on the requirements.  Is this task going to actually run on the server, or is it (as was originally proposed) just the same task that generates an additional file, and we'll continue to run it from development machines?

**Comment by mattpen** [comment]
This task will still run as originally proposed, on development machines. It doesn't actually generate an additional file, but calls creates a json object with the necessary data for the website and sends in in a POST request via an API I created.  The https module should work with the old servers as well (figaro and simian).

**Comment by pixelzoom** [comment]
Sounds good, thanks for the clarification.

**Comment by mattpen** [comment]
@pixelzoom @samreid - I've uploaded the script with changes so that it pushes the 3rd party licenses to the website.  The website on figaro currently does not have the API deployed, and since we are only 10 days away from the switch I will probably not deploy it before then.  I've tested the script on my local version of the website and it worked successfully, I'll test it on phet.colorado.edu after the switch.  The script will still create the file in sherpa even though the upload request is currently failing.

Would one of you be willing to review the changes and comment?

**Comment by pixelzoom** [comment]
I'm out until 8/4, can review it then unless @samreid gets to it sooner.

**Comment by samreid** [comment]
@mattpen is this line to drop the trailing comma?  It should be explained in a code comment:

```js
simLibraries = simLibraries.slice( 0, simLibraries.length - 1 ) + '}';
```

It may make things simpler to accumulate an array of data objects, then create the report string like this:
```js
`{` + elements.map(something).join(',')+'}'
```

It currently feels a bit confusing to have the opening `'{'` and closing `'}'` dislocated.

Why did you add force: true to the delete?  Please document in a code comment:

```js
grunt.file.delete( 'downloaded-sims', { force: true } );
```

**Comment by samreid** [comment]
I finished reviewing @mattpen's changes.  After @mattpen addresses the review suggestions, it would be good for @pixelzoom to take another look.

**Comment by mattpen** [comment]
@samreid - I made the changes you suggested above.  I removed the `{force:true}` entirely from the grunt.file.delete command.  It was not necessary.

**Comment by pixelzoom** [comment]
Results of running this task on my local machine:

```
% grunt report-third-party
...
downloading 71/72: https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en.html
downloading 72/72: https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_en.html
build-local.json is missing the value "websiteAuthorizationCode". The third party information was not uploaded to the website.  See a web developer for details.
File output changed, writing file ../sherpa/third-party-licenses.md

Done, without errors.
```

What is "websiteAuthorizationCode"? If it's required:

(1) Document it in the "usage" documentation.
(2) Check it *before* downloading html files.
(3) Fail if it's not present.

**Comment by mattpen** [comment]
The websiteAuthorizationCode is an authorization key for writing the post request.  It can be found under `"local-auth-code"` in `phet-server:/etc/tomcat/context.xml`.  I added an assertion for its presence at the beginning of the script.

I'll check that the script completes correctly on Wednesday after the server switchover.

**Comment by mattpen** [comment]
@pixelzoom ran the script today and it failed due to missing characters in the json that was sent to the website.  I'll take a look at this tomorrow.

**Comment by pixelzoom** [comment]
Also worth noting: plinks-probability was missing from the report, and the client-side script (`grunt report-third-party`) indicated success.

**Comment by mattpen** [comment]
The script is working again for ox-dev.  For example: https://ox-dev.colorado.edu/en/simulation/acid-base-solutions.  Plinko is still failing because it has not been copied over to ox-dev yet.  Running the script on phet.colorado.edu will need to wait on a deploy, which will probably happen on 10/2 or 10/3.

**Comment by mattpen** [comment]
Redeploy has been delayed due to delay in app publication.

**Comment by mattpen** [comment]
The script should now successfully update the website with the latest libraries.  I tested tonight and the libraries are present.  Closing.
