### ISSUE TITLE
toastr should be versioned

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#69]
toastr was added with this filename: toastr.min.js

It should be renamed to include the version number in the filename.

**Comment by samreid** [comment]
Please also update chipper/js/grunt/buildPhETIO.js when making this change.

**Comment by mattpen** [comment]
@samreid - I decided not to use this library after all and use jQueryUI instead. I'll remove it from sherpa, sherpa/lib/license.json and chipper/js/grunt/buildPhETIO.js.  Does it need to be removed from anywhere else?

**Comment by samreid** [comment]
Yes, .eslintrc has a toastr entry that should be removed.  Also I'd recommend searching all source for the string `toastr` just in case.

**Comment by mattpen** [comment]
toastr has been removed from all repos.
