### ISSUE TITLE
Why is this repo MIT when it is all contributed code?

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#72]
https://github.com/phetsims/tasks/issues/875

**Comment by samreid** [comment]
Scheduled for developer meeting to decide how to license this repo

**Comment by pixelzoom** [comment]
Licensing is outside of my area.

**Comment by jonathanolson** [comment]
Presumably each item is licensed individually, and the concept of "license for the repo" may not make sense?

**Comment by jbphet** [comment]
+1 for the suggestion that having a license doesn't make sense in this case.

**Comment by samreid** [comment]
See the license.json file

**Comment by samreid** [comment]
Updated, new version is here, closing:

https://github.com/phetsims/sherpa/blob/master/LICENSE.md
