### ISSUE TITLE
What syntax highlighter should we use? 

### ISSUE THREAD

**Issue by twant** [phetsims/sherpa#75]
@twant @jessegreenberg and @zepumph think It would be nice to use the same syntax highlighter for any displayed code. We've added Prism to sherpa as an option for this. 

@zepumph think Prism might fix this issue: https://github.com/phetsims/phet-io-wrappers/issues/203

**Comment by samreid** [comment]
Prism sounds promising but I don't think I'll have time to work on that soon.  Self-unassigning for now.

**Comment by samreid** [comment]
Highlight.js now supports line comments, after commits in the above issue.

**Comment by samreid** [comment]
Correct syntax highlighting for line comments caused all code to render in a single line on safari.  So we are moving toward Prism.  Highlight.js has been removed from master.  Closing.
