### ISSUE TITLE
SplitJS source map missing

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#77]
@pixelzoom said:

> In case it's significant... I'm seeing a new warning in Chrome 80.0.3987.100 console when loading any sim into Studio:

```
 DevTools failed to parse SourceMap: http://localhost/~cmalley/GitHub/sherpa/lib/split.min.js.map
```

**Comment by samreid** [comment]
It looks like Chrome didn’t used to report missing source maps, but now it does report them.
I can add that source map, but maybe we should also update to latest version of splitjs?

**Comment by samreid** [comment]
@pixelzoom said:

> Option 3 would be "just ignore it".

**Comment by samreid** [comment]
The minified source file has this line:

```js
//# sourceMappingURL=split.min.js.map
```

which causes it to look for the sourcemap.  We could download the sourcemap from https://cdnjs.cloudflare.com/ajax/libs/split.js/1.5.9/split.min.js.map, but it is not versioned or named like the rest of our sherpa assets.  Also, we don't want that file to be included in builds, or referenced in builds.

How about Option 4: Remove this line from our commits of split.js?

```js
//# sourceMappingURL=split.min.js.map
```

**Comment by pixelzoom** [comment]
I have no idea what split.js is, or what it's used for. So I'm probably not the best person to decide what the solution should be.  But in general, modifying a 3rd-party library usually results in increased upgrade cost, or (worse) the problem reappearing after upgrading.

**Comment by samreid** [comment]
Split.js is used to control the resize "panes" for studio:  https://split.js.org/

If I add the source map, the warning goes away for requirejs mode, but the warning is still present in built mode.  Which is confusing because I would have expected the build to strip out comments, including the sourcemap directive.

**Comment by samreid** [comment]
Some other options:

1. Strip out the sourcemap directive during build, in this part 

https://github.com/phetsims/chipper/blob/b2efd87f8301f70afea1f5b033a4d936734dce57/js/grunt/phet-io/copySupplementalPhetioFiles.js#L324-L338

2. Include the source build by adding it to contrib.  It is only 38kb.

@zepumph what do you recommend for this issue?

**Comment by zepumph** [comment]
I think we should ignore it, but if you don't like too much, then the best alternative to me is to "Include the source build by adding it to contrib. It is only 38kb."

**Comment by samreid** [comment]
I removed the sourcemap reference in the commit.  If we upgrade to a newer version, the warning will come back and we can decide how to proceed again.  Closing.  For now...
