### ISSUE TITLE
Is "contact phethelp@colorado.edu" a real license?

### ISSUE THREAD

**Issue by zepumph** [phetsims/sherpa#78]
Promoting TODO to an issue:

(also see https://github.com/phetsims/sherpa/issues/64#issuecomment-583150392)

While looking into un-issued TODOs in chipper, I found a todo added from this issue to `reportThirdParty.js`:

```

    // TODO: is this a real license?  Why is there logic here but nowhere else?  Perhaps files annotated with
    // TODO: contact phethelp@colorado.edu are leaking into the HTML files unnecessarily, see https://github.com/phetsims/sherpa/issues/64
    if ( license !== 'contact phethelp@colorado.edu' ) {
      mediaOutput.push( mediaEntryLines.join( '<br>' ) );

      if ( mediaLicensesUsed.indexOf( license ) < 0 ) {
        mediaLicensesUsed.push( license );
      }
    }
  }
```

This todo and `if` statement were added by @samreid, so assigning there.

**Comment by samreid** [comment]
I checked a built file and it did not include leak those files licensing information into the HTML file unnecessarily (other than the asset).  It's unclear where we would want to factor out usage of that license text for usage elsewhere, but we can always factor it out if we find a site later.  I'll remove the TODOs for now.

**Comment by samreid** [comment]
Removed the TODO, closing.
