### ISSUE TITLE
Move Font Awesome SVG data from FontAwesomeNode to sherpa/

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#82]
From #81 

@jonathanolson said:

> My concern is that the derived work is specifically embedded and checked into our MIT'ed source code, e.g. https://github.com/phetsims/sun/blob/master/js/FontAwesomeNode.js

I said:

> Maybe it would be more inline with PhET's process to put the font awesome data in the "sherpa" repo, which already supports various 3rd party licensing.

@kathy-phet said:

> I thought sherpa was just where we tracked the licenses? Is that were we put the third party images when we have them? If so, yes.

I said:

> Sherpa contains the 3rd party licenses as well as the 3rd party code.

@kathy-phet replied:

> If FontAwesome svgs can live there that is perfect.

**Comment by samreid** [comment]
In the commit, I moved the font awesome svg data from FontAwesomeNode to sherpa.  This was the "bare minimum" which kept the data in same form.  We will need further changes to accommodate new data from Font Awesome 5.0.  But I think that should be a new issue.  @jonathanolson can you please review this minor change?

**Comment by jonathanolson** [comment]
This looks good!
