### ISSUE TITLE
Imports for FA5 icons violate naming convention.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#86]
The convention for imports is that the import name should match the name of the file. For example:

GOOD: `import checkSolidShape from '../../../../sherpa/js/fontawesome-5/checkSolidShape.js';`
BAD: `import somethingDifferent from '../../../../sherpa/js/fontawesome-5/checkSolidShape.js';`

After the recent conversion to FA5, there are now some sims that are violating this convention. They are: 

- [ ] cck-black-box-study @samreid 

`import eyeShape from '../../../../sherpa/js/fontawesome-5/eyeSolidShape.js'`

- [x] expression-exchange @jbphet 

`import scissorsShape from '../../../../sherpa/js/fontawesome-5/cutSolidShape.js';`
`import exchangeShape from '../../../../sherpa/js/fontawesome-5/exchangeAltSolidShape.js';`

- [x] projectile-motion @jbphet 

`import editIconShape from '../../../../sherpa/js/fontawesome-5/editSolidShape.js';`

**Comment by pixelzoom** [comment]
I went ahead and fixed these. Feel free to close after reviewing.

**Comment by jbphet** [comment]
I inspected the changes for expression-exchange and made the change for projectile-motion.  It all looks good to me.

**Comment by samreid** [comment]
Looks good, thanks, closing.
