### ISSUE TITLE
Use FA5 trash alt regular for trash can icons

### ISSUE THREAD

**Issue by chrisklus** [phetsims/sherpa#88]
In a design meeting for https://github.com/phetsims/sherpa/issues/85, it was decided that FA5 "trash-alt regular" was the most desirable trash can icon. I several usages of `trashAltRegularShape`, but only one use of `trashSolidShape` in TrashButton in CCK. Assigning to @samreid to update usage(s).

**Comment by samreid** [comment]
Looks much better, thanks!  Closing.
