### ISSUE TITLE
Fontawesome *Shape.js files appear to be unnecessary. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#92]
Over in https://github.com/phetsims/sherpa/issues/83, we converted from fontawesome 4 to 5, and we ended up with a *String.js and a *Shape.js for every fontawesome 5 icon.  These live in sherpa/js/fontawesome5, and examples are:

```js
// cameraSolidString.js
export default 'M512 144v288c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V144c0-26.5 21.5-48 48-48h88l12.3-32.9c7-18.7 24.9-31.1 44.9-31.1h125.5c20 0 37.9 12.4 44.9 31.1L376 96h88c26.5 0 48 21.5 48 48zM376 288c0-66.2-53.8-120-120-120s-120 53.8-120 120 53.8 120 120 120 120-53.8 120-120zm-32 0c0 48.5-39.5 88-88 88s-88-39.5-88-88 39.5-88 88-88 88 39.5 88 88z';

// cameraSolidShape.js
import Shape from '../../../kite/js/Shape.js';
import cameraSolidString from './cameraSolidString.js';
export default new Shape( cameraSolidString );
```

What I discovered (quite by accident) is that the *Shape.js files appear to be unnecessary.  Path's constructor signature is:

`constructor( shape: Shape | string | null, options?: PathOptions )`

... so it will happily accept the *String.js file, and handle creation of the Shape.  

@samreid was there some other reason for creating the *Shape.js files?  If not, I recommend deleting them.

**Comment by samreid** [comment]
It takes a lot of CPU + time to parse a string into a Shape, so the *Shape.js files are provided as a way where that is factored out. So that if a simulation has N Shapes made of one icon, parsing still only happens once.

**Comment by pixelzoom** [comment]
Got it, thanks. Closing.
